trigger:
  # automatically runs on pull requests
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers
  branches:
    include:
      - dev
      - test
      - prod
  # only run for changes to Terraform files
  paths:
    include:
      - terraform/*
stages:
  - stage: plan
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: plan
        variables:
          - name: OTHER_SOURCE
            value: $[variables['System.PullRequest.SourceBranch']]
          - name: INDIVIDUAL_SOURCE
            value: $[variables['Build.SourceBranchName']]
          - name: TARGET
            value: $[variables['System.PullRequest.TargetBranch']]
        steps:
          # set the workspace variable at runtime (rather than build time) so that all the necessary variables are available, and we can use Python
          # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#about-tasksetvariable
          - bash: |
              WORKSPACE=$(python terraform/pipeline/workspace.py)
              echo "##vso[task.setvariable variable=workspace]$WORKSPACE"
            displayName: Determine deployment environment
            env:
              REASON: $(Build.Reason)
          # https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformInstaller#readme
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 1.3.1
          # https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformTask/TerraformTaskV3#readme
          - task: TerraformTaskV3@3
            displayName: Terraform init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#automated-terraform-cli-workflow
              commandOptions: -input=false
              # service connection
              backendServiceArm: deployer
              # needs to match main.tf
              backendAzureRmResourceGroupName: courtesy-cards-eligibility-terraform
              backendAzureRmStorageAccountName: courtesycardsterraform
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: terraform.tfstate
          - task: TerraformTaskV3@3
            displayName: Select environment
            inputs:
              provider: azurerm
              command: custom
              customCommand: workspace
              commandOptions: select $(workspace)
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # service connection
              environmentServiceNameAzureRM: deployer
          - task: TerraformTaskV3@3
            displayName: Terraform plan
            inputs:
              provider: azurerm
              command: plan
              # wait for lock to be released, in case being used by another pipeline run
              # https://discuss.hashicorp.com/t/terraform-plan-wait-for-lock-to-be-released/6870/2
              commandOptions: -input=false -lock-timeout=2m -out=tfplan
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # service connection
              environmentServiceNameAzureRM: deployer
          - task: TerraformTaskV3@3
            displayName: Terraform apply
            inputs:
              provider: azurerm
              command: apply
              # (ditto the lock comment above)
              commandOptions: -input=false -lock-timeout=2m tfplan
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
              # service connection
              environmentServiceNameAzureRM: deployer
            # only run on certain branches
            condition: in(variables['Build.SourceBranchName'], 'dev', 'test', 'prod')
